name: Tests
env:
  RAILS_ENV: test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rails_version:
          - 5.2.4.3
          - 6.0.3
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ matrix.rails_version }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-${{ matrix.rails_version }}-
      - name: Setup
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
        run: bundle install
      - name: Test
        run: bundle exec rake spec
